# Copyright 2025 Envy Group

name: Build Envy Kernel

on: [push, pull_request]

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  get-info:
    name: Info
    runs-on: ubuntu-24.04
    outputs:
      shorthash: ${{ steps.vars.outputs.shorthash }}
      commit: ${{ steps.vars.outputs.commit }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Commit Count and Git Hash
        id: vars
        run: |
          echo "shorthash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

  i386:
    name: i386
    runs-on: ubuntu-24.04
    needs: get-info
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Compile for i386
        env:
          BUILD_TYPE: ${{ env.BUILD_TYPE }}
          BUILD_DIR: ${{ env.BUILD_DIR }}
        run: |
          chmod +x ./Tools/Compilation/i386.sh
          ./Tools/Compilation/i386.sh
          echo Done testing